In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 50_Startups_dataset.csv to 50_Startups_dataset.csv

In [ ]:
dataset=pd.read_csv("/content/50_Startups_dataset.csv")
dataset

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,State,Profit
0,0,165349.30,136897.90,471784.20,New York,192261.93
1,1,162597.80,151377.69,443898.63,California,191792.16
2,2,153441.61,101145.65,407934.64,Florida,191050.49
3,3,144372.51,118671.95,383199.72,New York,182902.09
4,4,142107.44,91391.87,366168.52,Florida,166188.04
5,5,131877.00,99814.81,362861.46,New York,156991.22
6,6,134615.56,147198.97,127716.92,California,156122.61
7,7,130298.23,145530.16,323876.78,Florida,155752.70
8,8,120542.62,148719.05,311613.39,New York,152211.87
9,9,123334.98,108679.27,304981.72,California,149760.06
10,10,101913.18,110594.21,229161.05,Florida,146122.05
11,11,100672.06,91790.71,249744.65,California,144259.50
12,12,93863.85,127320.48,249839.54,Florida,141585.62
13,13,91992.49,135495.17,252665.03,California,134307.45
14,14,119943.34,156547.52,256513.02,Florida,132602.75
15,15,114523.71,122616.94,261776.33,New York,129917.14
16,16,78013.21,121597.65,264346.16,California,126993.03
17,17,94657.26,145077.68,282574.41,New York,125370.47
18,18,91749.26,114175.89,294919.67,Florida,124267.00
19,19,86419.80,153514.21,0.10,New York,122776.96
20,20,76253.96,113867.40,298664.57,California,118474.13
21,21,78389.57,153773.53,299737.39,New York,111313.12
22,22,73994.66,122782.85,303319.36,Florida,110352.35
23,23,67532.63,105751.13,304768.83,Florida,108734.09
24,24,77044.11,99281.44,140574.91,New York,108552.14
25,25,64664.81,139553.26,137962.72,California,107404.44
26,26,75328.97,144136.08,134050.17,Florida,105733.64
27,27,72107.70,127864.65,353183.91,New York,105008.41
28,28,66051.62,182645.66,118148.30,Florida,103282.48
29,29,65605.58,153032.16,107138.48,New York,101004.74
30,30,61994.58,115641.38,91131.34,Florida,99937.69
31,31,61136.48,152702.02,88218.33,New York,97483.66
32,32,63408.96,129219.71,46085.35,California,97427.94
33,33,55494.05,103057.59,214634.91,Florida,96779.02
34,34,46426.17,157694.02,210797.77,California,96712.90
35,35,46014.12,85047.54,205517.74,New York,96479.61
36,36,28663.86,127056.31,201126.92,Florida,90708.29
37,37,44070.05,51283.24,197029.52,California,89949.24
38,38,20229.69,65948.03,185265.20,New York,81229.16
39,39,38558.61,82982.19,174999.40,California,81005.86
40,40,28754.43,118546.15,172795.77,California,78240.01
41,41,27893.02,84710.87,164470.81,Florida,77798.93
42,42,23641.03,96189.73,148001.21,California,71498.59
43,43,15505.83,127382.40,35534.27,New York,69759.08
44,44,22177.84,154806.24,28334.82,California,65200.43
45,45,1000.33,124153.14,1904.03,New York,64926.18
46,46,1315.56,115816.31,297114.56,Florida,49490.85
47,47,0.10,135427.02,0.10,California,42559.83
48,48,542.15,51743.25,0.10,New York,35673.51
49,49,0.10,116983.90,45173.16,California,14681.50

In [ ]:
ColumnsName = dataset.columns

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       50 non-null     int64
 1   R&D Spend        50 non-null     float64
 2   Administration   50 non-null     float64
 3   Marketing Spend  50 non-null     float64
 4   State            50 non-null     object
 5   Profit           50 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.5+ KB

In [ ]:
ColumnsName

Index(['Unnamed: 0', 'R&D Spend', 'Administration', 'Marketing Spend', 'State',
       'Profit'],
      dtype='object')

In [ ]:
dataset["Profit"].dtype

dtype('float64')

In [ ]:
dataset["R&D Spend"].dtype

dtype('float64')

In [ ]:
quan = []
qual = []
for ch in ColumnsName:
  if dataset[ch].dtype == "O":
    #print("qual")
    qual.append(ch)
  else:
    #print("quan")
    quan.append(ch)

In [ ]:
quan

['Unnamed: 0', 'R&D Spend', 'Administration', 'Marketing Spend', 'Profit']

In [ ]:
qual

['State']

In [ ]:
def quanqual(dataset):
  quan = []
  qual = []
  for ch in  dataset.columns:
    if dataset[ch].dtype == "O":
      #print("qual")
      qual.append(ch)
    else:
      #print("quan")
      quan.append(ch)
  return quan,qual

In [ ]:
quan,qual = quanqual(dataset)

In [ ]:
quan

['Unnamed: 0', 'R&D Spend', 'Administration', 'Marketing Spend', 'Profit']

In [ ]:
qual

['State']

In [ ]:
dataset[quan]

    Unnamed: 0  R&D Spend  Administration  Marketing Spend     Profit
0            0  165349.30       136897.90        471784.20  192261.93
1            1  162597.80       151377.69        443898.63  191792.16
2            2  153441.61       101145.65        407934.64  191050.49
3            3  144372.51       118671.95        383199.72  182902.09
4            4  142107.44        91391.87        366168.52  166188.04
5            5  131877.00        99814.81        362861.46  156991.22
6            6  134615.56       147198.97        127716.92  156122.61
7            7  130298.23       145530.16        323876.78  155752.70
8            8  120542.62       148719.05        311613.39  152211.87
9            9  123334.98       108679.27        304981.72  149760.06
10          10  101913.18       110594.21        229161.05  146122.05
11          11  100672.06        91790.71        249744.65  144259.50
12          12   93863.85       127320.48        249839.54  141585.62
13          13   91992.49       135495.17        252665.03  134307.45
14          14  119943.34       156547.52        256513.02  132602.75
15          15  114523.71       122616.94        261776.33  129917.14
16          16   78013.21       121597.65        264346.16  126993.03
17          17   94657.26       145077.68        282574.41  125370.47
18          18   91749.26       114175.89        294919.67  124267.00
19          19   86419.80       153514.21             0.10  122776.96
20          20   76253.96       113867.40        298664.57  118474.13
21          21   78389.57       153773.53        299737.39  111313.12
22          22   73994.66       122782.85        303319.36  110352.35
23          23   67532.63       105751.13        304768.83  108734.09
24          24   77044.11        99281.44        140574.91  108552.14
25          25   64664.81       139553.26        137962.72  107404.44
26          26   75328.97       144136.08        134050.17  105733.64
27          27   72107.70       127864.65        353183.91  105008.41
28          28   66051.62       182645.66        118148.30  103282.48
29          29   65605.58       153032.16        107138.48  101004.74
30          30   61994.58       115641.38         91131.34   99937.69
31          31   61136.48       152702.02         88218.33   97483.66
32          32   63408.96       129219.71         46085.35   97427.94
33          33   55494.05       103057.59        214634.91   96779.02
34          34   46426.17       157694.02        210797.77   96712.90
35          35   46014.12        85047.54        205517.74   96479.61
36          36   28663.86       127056.31        201126.92   90708.29
37          37   44070.05        51283.24        197029.52   89949.24
38          38   20229.69        65948.03        185265.20   81229.16
39          39   38558.61        82982.19        174999.40   81005.86
40          40   28754.43       118546.15        172795.77   78240.01
41          41   27893.02        84710.87        164470.81   77798.93
42          42   23641.03        96189.73        148001.21   71498.59
43          43   15505.83       127382.40         35534.27   69759.08
44          44   22177.84       154806.24         28334.82   65200.43
45          45    1000.33       124153.14          1904.03   64926.18
46          46    1315.56       115816.31        297114.56   49490.85
47          47       0.10       135427.02             0.10   42559.83
48          48     542.15        51743.25             0.10   35673.51
49          49       0.10       116983.90         45173.16   14681.50

In [ ]:
dataset[qual]

         State
0     New York
1   California
2      Florida
3     New York
4      Florida
5     New York
6   California
7      Florida
8     New York
9   California
10     Florida
11  California
12     Florida
13  California
14     Florida
15    New York
16  California
17    New York
18     Florida
19    New York
20  California
21    New York
22     Florida
23     Florida
24    New York
25  California
26     Florida
27    New York
28     Florida
29    New York
30     Florida
31    New York
32  California
33     Florida
34  California
35    New York
36     Florida
37  California
38    New York
39  California
40  California
41     Florida
42  California
43    New York
44  California
45    New York
46     Florida
47  California
48    New York
49  California

In [ ]:
dir()

['ColumnsName',
 'In',
 'Out',
 '_',
 '_1',
 '_11',
 '_12',
 '_13',
 '_15',
 '_16',
 '_19',
 '_20',
 '_21',
 '_22',
 '_7',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'ch',
 'dataset',
 'exit',
 'files',
 'get_ipython',
 'pd',
 'qual',
 'quan',
 'quanqual',
 'quit',
 'uploaded']

In [ ]:
dir(dataset)

['Administration',
 'Profit',
 'State',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [29]:
dataset["Profit"].mean()

np.float64(112012.73919999998)

In [30]:
dataset["Profit"].median()

107978.29000000001

In [31]:
dataset["Profit"].mode()[0]

np.float64(14681.5)